// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

#ifndef PROTOBUF_game_2eproto__INCLUDED
#define PROTOBUF_game_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)

namespace MSG {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_game_2eproto();
void protobuf_AssignDesc_game_2eproto();
void protobuf_ShutdownFile_game_2eproto();

class BattleLogAns;
class BattleLogReq;
class ContentsNot;
class CreateCharAns;
class CreateCharReq;
class CurrencyNot;
class LevelupCharAns;
class LevelupCharReq;
class PlayDungeonAns;
class PlayDungeonNot;
class PlayDungeonNot_DungeonPlay;
class PlayDungeonReq;
class TierupCharAns;
class TierupCharReq;

// ===================================================================

class ContentsNot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MSG.ContentsNot) */ {
 public:
  ContentsNot();
  virtual ~ContentsNot();

  ContentsNot(const ContentsNot& from);

  inline ContentsNot& operator=(const ContentsNot& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ContentsNot& default_instance();

  void Swap(ContentsNot* other);

  // implements Message ----------------------------------------------

  inline ContentsNot* New() const { return New(NULL); }

  ContentsNot* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ContentsNot& from);
  void MergeFrom(const ContentsNot& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ContentsNot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string contents = 1;
  int contents_size() const;
  void clear_contents();
  static const int kContentsFieldNumber = 1;
  const ::std::string& contents(int index) const;
  ::std::string* mutable_contents(int index);
  void set_contents(int index, const ::std::string& value);
  void set_contents(int index, const char* value);
  void set_contents(int index, const char* value, size_t size);
  ::std::string* add_contents();
  void add_contents(const ::std::string& value);
  void add_contents(const char* value);
  void add_contents(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& contents() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_contents();

  // optional uint32 dungeonNo = 2;
  void clear_dungeonno();
  static const int kDungeonNoFieldNumber = 2;
  ::google::protobuf::uint32 dungeonno() const;
  void set_dungeonno(::google::protobuf::uint32 value);

  // optional uint32 tier = 3;
  void clear_tier();
  static const int kTierFieldNumber = 3;
  ::google::protobuf::uint32 tier() const;
  void set_tier(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MSG.ContentsNot)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::std::string> contents_;
  ::google::protobuf::uint32 dungeonno_;
  ::google::protobuf::uint32 tier_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_2eproto();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static ContentsNot* default_instance_;
};
// -------------------------------------------------------------------

class PlayDungeonNot_DungeonPlay : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MSG.PlayDungeonNot.DungeonPlay) */ {
 public:
  PlayDungeonNot_DungeonPlay();
  virtual ~PlayDungeonNot_DungeonPlay();

  PlayDungeonNot_DungeonPlay(const PlayDungeonNot_DungeonPlay& from);

  inline PlayDungeonNot_DungeonPlay& operator=(const PlayDungeonNot_DungeonPlay& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayDungeonNot_DungeonPlay& default_instance();

  void Swap(PlayDungeonNot_DungeonPlay* other);

  // implements Message ----------------------------------------------

  inline PlayDungeonNot_DungeonPlay* New() const { return New(NULL); }

  PlayDungeonNot_DungeonPlay* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayDungeonNot_DungeonPlay& from);
  void MergeFrom(const PlayDungeonNot_DungeonPlay& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PlayDungeonNot_DungeonPlay* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 dungeonNo = 1;
  void clear_dungeonno();
  static const int kDungeonNoFieldNumber = 1;
  ::google::protobuf::uint32 dungeonno() const;
  void set_dungeonno(::google::protobuf::uint32 value);

  // optional uint32 tier = 2;
  void clear_tier();
  static const int kTierFieldNumber = 2;
  ::google::protobuf::uint32 tier() const;
  void set_tier(::google::protobuf::uint32 value);

  // repeated .MSG.BattleData_ battles = 3;
  int battles_size() const;
  void clear_battles();
  static const int kBattlesFieldNumber = 3;
  const ::MSG::BattleData_& battles(int index) const;
  ::MSG::BattleData_* mutable_battles(int index);
  ::MSG::BattleData_* add_battles();
  ::google::protobuf::RepeatedPtrField< ::MSG::BattleData_ >*
      mutable_battles();
  const ::google::protobuf::RepeatedPtrField< ::MSG::BattleData_ >&
      battles() const;

  // repeated .MSG.CharData_ chars = 4;
  int chars_size() const;
  void clear_chars();
  static const int kCharsFieldNumber = 4;
  const ::MSG::CharData_& chars(int index) const;
  ::MSG::CharData_* mutable_chars(int index);
  ::MSG::CharData_* add_chars();
  ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >*
      mutable_chars();
  const ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >&
      chars() const;

  // repeated .MSG.CharData_ mobs = 5;
  int mobs_size() const;
  void clear_mobs();
  static const int kMobsFieldNumber = 5;
  const ::MSG::CharData_& mobs(int index) const;
  ::MSG::CharData_* mutable_mobs(int index);
  ::MSG::CharData_* add_mobs();
  ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >*
      mutable_mobs();
  const ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >&
      mobs() const;

  // @@protoc_insertion_point(class_scope:MSG.PlayDungeonNot.DungeonPlay)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 dungeonno_;
  ::google::protobuf::uint32 tier_;
  ::google::protobuf::RepeatedPtrField< ::MSG::BattleData_ > battles_;
  ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ > chars_;
  ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ > mobs_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_2eproto();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static PlayDungeonNot_DungeonPlay* default_instance_;
};
// -------------------------------------------------------------------

class PlayDungeonNot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MSG.PlayDungeonNot) */ {
 public:
  PlayDungeonNot();
  virtual ~PlayDungeonNot();

  PlayDungeonNot(const PlayDungeonNot& from);

  inline PlayDungeonNot& operator=(const PlayDungeonNot& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayDungeonNot& default_instance();

  void Swap(PlayDungeonNot* other);

  // implements Message ----------------------------------------------

  inline PlayDungeonNot* New() const { return New(NULL); }

  PlayDungeonNot* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayDungeonNot& from);
  void MergeFrom(const PlayDungeonNot& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PlayDungeonNot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef PlayDungeonNot_DungeonPlay DungeonPlay;

  // accessors -------------------------------------------------------

  // repeated .MSG.PlayDungeonNot.DungeonPlay plays = 1;
  int plays_size() const;
  void clear_plays();
  static const int kPlaysFieldNumber = 1;
  const ::MSG::PlayDungeonNot_DungeonPlay& plays(int index) const;
  ::MSG::PlayDungeonNot_DungeonPlay* mutable_plays(int index);
  ::MSG::PlayDungeonNot_DungeonPlay* add_plays();
  ::google::protobuf::RepeatedPtrField< ::MSG::PlayDungeonNot_DungeonPlay >*
      mutable_plays();
  const ::google::protobuf::RepeatedPtrField< ::MSG::PlayDungeonNot_DungeonPlay >&
      plays() const;

  // @@protoc_insertion_point(class_scope:MSG.PlayDungeonNot)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::MSG::PlayDungeonNot_DungeonPlay > plays_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_2eproto();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static PlayDungeonNot* default_instance_;
};
// -------------------------------------------------------------------

class CreateCharReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MSG.CreateCharReq) */ {
 public:
  CreateCharReq();
  virtual ~CreateCharReq();

  CreateCharReq(const CreateCharReq& from);

  inline CreateCharReq& operator=(const CreateCharReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateCharReq& default_instance();

  void Swap(CreateCharReq* other);

  // implements Message ----------------------------------------------

  inline CreateCharReq* New() const { return New(NULL); }

  CreateCharReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CreateCharReq& from);
  void MergeFrom(const CreateCharReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CreateCharReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 charNo = 1;
  void clear_charno();
  static const int kCharNoFieldNumber = 1;
  ::google::protobuf::uint32 charno() const;
  void set_charno(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MSG.CreateCharReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 charno_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_2eproto();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static CreateCharReq* default_instance_;
};
// -------------------------------------------------------------------

class CreateCharAns : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MSG.CreateCharAns) */ {
 public:
  CreateCharAns();
  virtual ~CreateCharAns();

  CreateCharAns(const CreateCharAns& from);

  inline CreateCharAns& operator=(const CreateCharAns& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateCharAns& default_instance();

  void Swap(CreateCharAns* other);

  // implements Message ----------------------------------------------

  inline CreateCharAns* New() const { return New(NULL); }

  CreateCharAns* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CreateCharAns& from);
  void MergeFrom(const CreateCharAns& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CreateCharAns* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MSG.ErrorCode err = 1;
  void clear_err();
  static const int kErrFieldNumber = 1;
  ::MSG::ErrorCode err() const;
  void set_err(::MSG::ErrorCode value);

  // optional .MSG.CharData_ char_ = 2;
  bool has_char_() const;
  void clear_char_();
  static const int kCharFieldNumber = 2;
  const ::MSG::CharData_& char_() const;
  ::MSG::CharData_* mutable_char_();
  ::MSG::CharData_* release_char_();
  void set_allocated_char_(::MSG::CharData_* char_);

  // @@protoc_insertion_point(class_scope:MSG.CreateCharAns)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::MSG::CharData_* char__;
  int err_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_2eproto();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static CreateCharAns* default_instance_;
};
// -------------------------------------------------------------------

class CurrencyNot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MSG.CurrencyNot) */ {
 public:
  CurrencyNot();
  virtual ~CurrencyNot();

  CurrencyNot(const CurrencyNot& from);

  inline CurrencyNot& operator=(const CurrencyNot& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CurrencyNot& default_instance();

  void Swap(CurrencyNot* other);

  // implements Message ----------------------------------------------

  inline CurrencyNot* New() const { return New(NULL); }

  CurrencyNot* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CurrencyNot& from);
  void MergeFrom(const CurrencyNot& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CurrencyNot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 vc1 = 1;
  void clear_vc1();
  static const int kVc1FieldNumber = 1;
  ::google::protobuf::uint32 vc1() const;
  void set_vc1(::google::protobuf::uint32 value);

  // optional uint32 vc2 = 2;
  void clear_vc2();
  static const int kVc2FieldNumber = 2;
  ::google::protobuf::uint32 vc2() const;
  void set_vc2(::google::protobuf::uint32 value);

  // optional uint32 vc3 = 3;
  void clear_vc3();
  static const int kVc3FieldNumber = 3;
  ::google::protobuf::uint32 vc3() const;
  void set_vc3(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MSG.CurrencyNot)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 vc1_;
  ::google::protobuf::uint32 vc2_;
  ::google::protobuf::uint32 vc3_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_2eproto();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static CurrencyNot* default_instance_;
};
// -------------------------------------------------------------------

class PlayDungeonReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MSG.PlayDungeonReq) */ {
 public:
  PlayDungeonReq();
  virtual ~PlayDungeonReq();

  PlayDungeonReq(const PlayDungeonReq& from);

  inline PlayDungeonReq& operator=(const PlayDungeonReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayDungeonReq& default_instance();

  void Swap(PlayDungeonReq* other);

  // implements Message ----------------------------------------------

  inline PlayDungeonReq* New() const { return New(NULL); }

  PlayDungeonReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayDungeonReq& from);
  void MergeFrom(const PlayDungeonReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PlayDungeonReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 dungeonNo = 1;
  void clear_dungeonno();
  static const int kDungeonNoFieldNumber = 1;
  ::google::protobuf::uint32 dungeonno() const;
  void set_dungeonno(::google::protobuf::uint32 value);

  // optional uint32 tier = 2;
  void clear_tier();
  static const int kTierFieldNumber = 2;
  ::google::protobuf::uint32 tier() const;
  void set_tier(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MSG.PlayDungeonReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 dungeonno_;
  ::google::protobuf::uint32 tier_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_2eproto();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static PlayDungeonReq* default_instance_;
};
// -------------------------------------------------------------------

class PlayDungeonAns : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MSG.PlayDungeonAns) */ {
 public:
  PlayDungeonAns();
  virtual ~PlayDungeonAns();

  PlayDungeonAns(const PlayDungeonAns& from);

  inline PlayDungeonAns& operator=(const PlayDungeonAns& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayDungeonAns& default_instance();

  void Swap(PlayDungeonAns* other);

  // implements Message ----------------------------------------------

  inline PlayDungeonAns* New() const { return New(NULL); }

  PlayDungeonAns* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayDungeonAns& from);
  void MergeFrom(const PlayDungeonAns& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PlayDungeonAns* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MSG.ErrorCode err = 1;
  void clear_err();
  static const int kErrFieldNumber = 1;
  ::MSG::ErrorCode err() const;
  void set_err(::MSG::ErrorCode value);

  // repeated .MSG.BattleData_ battles = 2;
  int battles_size() const;
  void clear_battles();
  static const int kBattlesFieldNumber = 2;
  const ::MSG::BattleData_& battles(int index) const;
  ::MSG::BattleData_* mutable_battles(int index);
  ::MSG::BattleData_* add_battles();
  ::google::protobuf::RepeatedPtrField< ::MSG::BattleData_ >*
      mutable_battles();
  const ::google::protobuf::RepeatedPtrField< ::MSG::BattleData_ >&
      battles() const;

  // repeated .MSG.CharData_ chars = 3;
  int chars_size() const;
  void clear_chars();
  static const int kCharsFieldNumber = 3;
  const ::MSG::CharData_& chars(int index) const;
  ::MSG::CharData_* mutable_chars(int index);
  ::MSG::CharData_* add_chars();
  ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >*
      mutable_chars();
  const ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >&
      chars() const;

  // repeated .MSG.CharData_ mobs = 4;
  int mobs_size() const;
  void clear_mobs();
  static const int kMobsFieldNumber = 4;
  const ::MSG::CharData_& mobs(int index) const;
  ::MSG::CharData_* mutable_mobs(int index);
  ::MSG::CharData_* add_mobs();
  ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >*
      mutable_mobs();
  const ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >&
      mobs() const;

  // optional .MSG.BattleData_ winner = 5;
  bool has_winner() const;
  void clear_winner();
  static const int kWinnerFieldNumber = 5;
  const ::MSG::BattleData_& winner() const;
  ::MSG::BattleData_* mutable_winner();
  ::MSG::BattleData_* release_winner();
  void set_allocated_winner(::MSG::BattleData_* winner);

  // @@protoc_insertion_point(class_scope:MSG.PlayDungeonAns)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::MSG::BattleData_ > battles_;
  ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ > chars_;
  ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ > mobs_;
  ::MSG::BattleData_* winner_;
  int err_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_2eproto();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static PlayDungeonAns* default_instance_;
};
// -------------------------------------------------------------------

class LevelupCharReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MSG.LevelupCharReq) */ {
 public:
  LevelupCharReq();
  virtual ~LevelupCharReq();

  LevelupCharReq(const LevelupCharReq& from);

  inline LevelupCharReq& operator=(const LevelupCharReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LevelupCharReq& default_instance();

  void Swap(LevelupCharReq* other);

  // implements Message ----------------------------------------------

  inline LevelupCharReq* New() const { return New(NULL); }

  LevelupCharReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LevelupCharReq& from);
  void MergeFrom(const LevelupCharReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LevelupCharReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 slotNo = 1;
  void clear_slotno();
  static const int kSlotNoFieldNumber = 1;
  ::google::protobuf::uint32 slotno() const;
  void set_slotno(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MSG.LevelupCharReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 slotno_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_2eproto();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static LevelupCharReq* default_instance_;
};
// -------------------------------------------------------------------

class LevelupCharAns : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MSG.LevelupCharAns) */ {
 public:
  LevelupCharAns();
  virtual ~LevelupCharAns();

  LevelupCharAns(const LevelupCharAns& from);

  inline LevelupCharAns& operator=(const LevelupCharAns& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LevelupCharAns& default_instance();

  void Swap(LevelupCharAns* other);

  // implements Message ----------------------------------------------

  inline LevelupCharAns* New() const { return New(NULL); }

  LevelupCharAns* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LevelupCharAns& from);
  void MergeFrom(const LevelupCharAns& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LevelupCharAns* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MSG.ErrorCode err = 1;
  void clear_err();
  static const int kErrFieldNumber = 1;
  ::MSG::ErrorCode err() const;
  void set_err(::MSG::ErrorCode value);

  // optional .MSG.CharData_ char_ = 2;
  bool has_char_() const;
  void clear_char_();
  static const int kCharFieldNumber = 2;
  const ::MSG::CharData_& char_() const;
  ::MSG::CharData_* mutable_char_();
  ::MSG::CharData_* release_char_();
  void set_allocated_char_(::MSG::CharData_* char_);

  // @@protoc_insertion_point(class_scope:MSG.LevelupCharAns)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::MSG::CharData_* char__;
  int err_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_2eproto();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static LevelupCharAns* default_instance_;
};
// -------------------------------------------------------------------

class TierupCharReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MSG.TierupCharReq) */ {
 public:
  TierupCharReq();
  virtual ~TierupCharReq();

  TierupCharReq(const TierupCharReq& from);

  inline TierupCharReq& operator=(const TierupCharReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TierupCharReq& default_instance();

  void Swap(TierupCharReq* other);

  // implements Message ----------------------------------------------

  inline TierupCharReq* New() const { return New(NULL); }

  TierupCharReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TierupCharReq& from);
  void MergeFrom(const TierupCharReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TierupCharReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 slotNo = 1;
  void clear_slotno();
  static const int kSlotNoFieldNumber = 1;
  ::google::protobuf::uint32 slotno() const;
  void set_slotno(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MSG.TierupCharReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 slotno_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_2eproto();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static TierupCharReq* default_instance_;
};
// -------------------------------------------------------------------

class TierupCharAns : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MSG.TierupCharAns) */ {
 public:
  TierupCharAns();
  virtual ~TierupCharAns();

  TierupCharAns(const TierupCharAns& from);

  inline TierupCharAns& operator=(const TierupCharAns& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TierupCharAns& default_instance();

  void Swap(TierupCharAns* other);

  // implements Message ----------------------------------------------

  inline TierupCharAns* New() const { return New(NULL); }

  TierupCharAns* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TierupCharAns& from);
  void MergeFrom(const TierupCharAns& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TierupCharAns* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MSG.ErrorCode err = 1;
  void clear_err();
  static const int kErrFieldNumber = 1;
  ::MSG::ErrorCode err() const;
  void set_err(::MSG::ErrorCode value);

  // optional .MSG.CharData_ char_ = 2;
  bool has_char_() const;
  void clear_char_();
  static const int kCharFieldNumber = 2;
  const ::MSG::CharData_& char_() const;
  ::MSG::CharData_* mutable_char_();
  ::MSG::CharData_* release_char_();
  void set_allocated_char_(::MSG::CharData_* char_);

  // @@protoc_insertion_point(class_scope:MSG.TierupCharAns)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::MSG::CharData_* char__;
  int err_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_2eproto();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static TierupCharAns* default_instance_;
};
// -------------------------------------------------------------------

class BattleLogReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MSG.BattleLogReq) */ {
 public:
  BattleLogReq();
  virtual ~BattleLogReq();

  BattleLogReq(const BattleLogReq& from);

  inline BattleLogReq& operator=(const BattleLogReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BattleLogReq& default_instance();

  void Swap(BattleLogReq* other);

  // implements Message ----------------------------------------------

  inline BattleLogReq* New() const { return New(NULL); }

  BattleLogReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BattleLogReq& from);
  void MergeFrom(const BattleLogReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BattleLogReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 lid = 1;
  void clear_lid();
  static const int kLidFieldNumber = 1;
  ::google::protobuf::uint64 lid() const;
  void set_lid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:MSG.BattleLogReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 lid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_2eproto();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static BattleLogReq* default_instance_;
};
// -------------------------------------------------------------------

class BattleLogAns : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MSG.BattleLogAns) */ {
 public:
  BattleLogAns();
  virtual ~BattleLogAns();

  BattleLogAns(const BattleLogAns& from);

  inline BattleLogAns& operator=(const BattleLogAns& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BattleLogAns& default_instance();

  void Swap(BattleLogAns* other);

  // implements Message ----------------------------------------------

  inline BattleLogAns* New() const { return New(NULL); }

  BattleLogAns* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BattleLogAns& from);
  void MergeFrom(const BattleLogAns& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BattleLogAns* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MSG.ErrorCode err = 1;
  void clear_err();
  static const int kErrFieldNumber = 1;
  ::MSG::ErrorCode err() const;
  void set_err(::MSG::ErrorCode value);

  // repeated .MSG.DungeonPlayData_ data = 2;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 2;
  const ::MSG::DungeonPlayData_& data(int index) const;
  ::MSG::DungeonPlayData_* mutable_data(int index);
  ::MSG::DungeonPlayData_* add_data();
  ::google::protobuf::RepeatedPtrField< ::MSG::DungeonPlayData_ >*
      mutable_data();
  const ::google::protobuf::RepeatedPtrField< ::MSG::DungeonPlayData_ >&
      data() const;

  // @@protoc_insertion_point(class_scope:MSG.BattleLogAns)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::MSG::DungeonPlayData_ > data_;
  int err_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_game_2eproto();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static BattleLogAns* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ContentsNot

// repeated string contents = 1;
inline int ContentsNot::contents_size() const {
  return contents_.size();
}
inline void ContentsNot::clear_contents() {
  contents_.Clear();
}
inline const ::std::string& ContentsNot::contents(int index) const {
  // @@protoc_insertion_point(field_get:MSG.ContentsNot.contents)
  return contents_.Get(index);
}
inline ::std::string* ContentsNot::mutable_contents(int index) {
  // @@protoc_insertion_point(field_mutable:MSG.ContentsNot.contents)
  return contents_.Mutable(index);
}
inline void ContentsNot::set_contents(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:MSG.ContentsNot.contents)
  contents_.Mutable(index)->assign(value);
}
inline void ContentsNot::set_contents(int index, const char* value) {
  contents_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:MSG.ContentsNot.contents)
}
inline void ContentsNot::set_contents(int index, const char* value, size_t size) {
  contents_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MSG.ContentsNot.contents)
}
inline ::std::string* ContentsNot::add_contents() {
  // @@protoc_insertion_point(field_add_mutable:MSG.ContentsNot.contents)
  return contents_.Add();
}
inline void ContentsNot::add_contents(const ::std::string& value) {
  contents_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:MSG.ContentsNot.contents)
}
inline void ContentsNot::add_contents(const char* value) {
  contents_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:MSG.ContentsNot.contents)
}
inline void ContentsNot::add_contents(const char* value, size_t size) {
  contents_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:MSG.ContentsNot.contents)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ContentsNot::contents() const {
  // @@protoc_insertion_point(field_list:MSG.ContentsNot.contents)
  return contents_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ContentsNot::mutable_contents() {
  // @@protoc_insertion_point(field_mutable_list:MSG.ContentsNot.contents)
  return &contents_;
}

// optional uint32 dungeonNo = 2;
inline void ContentsNot::clear_dungeonno() {
  dungeonno_ = 0u;
}
inline ::google::protobuf::uint32 ContentsNot::dungeonno() const {
  // @@protoc_insertion_point(field_get:MSG.ContentsNot.dungeonNo)
  return dungeonno_;
}
inline void ContentsNot::set_dungeonno(::google::protobuf::uint32 value) {
  
  dungeonno_ = value;
  // @@protoc_insertion_point(field_set:MSG.ContentsNot.dungeonNo)
}

// optional uint32 tier = 3;
inline void ContentsNot::clear_tier() {
  tier_ = 0u;
}
inline ::google::protobuf::uint32 ContentsNot::tier() const {
  // @@protoc_insertion_point(field_get:MSG.ContentsNot.tier)
  return tier_;
}
inline void ContentsNot::set_tier(::google::protobuf::uint32 value) {
  
  tier_ = value;
  // @@protoc_insertion_point(field_set:MSG.ContentsNot.tier)
}

// -------------------------------------------------------------------

// PlayDungeonNot_DungeonPlay

// optional uint32 dungeonNo = 1;
inline void PlayDungeonNot_DungeonPlay::clear_dungeonno() {
  dungeonno_ = 0u;
}
inline ::google::protobuf::uint32 PlayDungeonNot_DungeonPlay::dungeonno() const {
  // @@protoc_insertion_point(field_get:MSG.PlayDungeonNot.DungeonPlay.dungeonNo)
  return dungeonno_;
}
inline void PlayDungeonNot_DungeonPlay::set_dungeonno(::google::protobuf::uint32 value) {
  
  dungeonno_ = value;
  // @@protoc_insertion_point(field_set:MSG.PlayDungeonNot.DungeonPlay.dungeonNo)
}

// optional uint32 tier = 2;
inline void PlayDungeonNot_DungeonPlay::clear_tier() {
  tier_ = 0u;
}
inline ::google::protobuf::uint32 PlayDungeonNot_DungeonPlay::tier() const {
  // @@protoc_insertion_point(field_get:MSG.PlayDungeonNot.DungeonPlay.tier)
  return tier_;
}
inline void PlayDungeonNot_DungeonPlay::set_tier(::google::protobuf::uint32 value) {
  
  tier_ = value;
  // @@protoc_insertion_point(field_set:MSG.PlayDungeonNot.DungeonPlay.tier)
}

// repeated .MSG.BattleData_ battles = 3;
inline int PlayDungeonNot_DungeonPlay::battles_size() const {
  return battles_.size();
}
inline void PlayDungeonNot_DungeonPlay::clear_battles() {
  battles_.Clear();
}
inline const ::MSG::BattleData_& PlayDungeonNot_DungeonPlay::battles(int index) const {
  // @@protoc_insertion_point(field_get:MSG.PlayDungeonNot.DungeonPlay.battles)
  return battles_.Get(index);
}
inline ::MSG::BattleData_* PlayDungeonNot_DungeonPlay::mutable_battles(int index) {
  // @@protoc_insertion_point(field_mutable:MSG.PlayDungeonNot.DungeonPlay.battles)
  return battles_.Mutable(index);
}
inline ::MSG::BattleData_* PlayDungeonNot_DungeonPlay::add_battles() {
  // @@protoc_insertion_point(field_add:MSG.PlayDungeonNot.DungeonPlay.battles)
  return battles_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::MSG::BattleData_ >*
PlayDungeonNot_DungeonPlay::mutable_battles() {
  // @@protoc_insertion_point(field_mutable_list:MSG.PlayDungeonNot.DungeonPlay.battles)
  return &battles_;
}
inline const ::google::protobuf::RepeatedPtrField< ::MSG::BattleData_ >&
PlayDungeonNot_DungeonPlay::battles() const {
  // @@protoc_insertion_point(field_list:MSG.PlayDungeonNot.DungeonPlay.battles)
  return battles_;
}

// repeated .MSG.CharData_ chars = 4;
inline int PlayDungeonNot_DungeonPlay::chars_size() const {
  return chars_.size();
}
inline void PlayDungeonNot_DungeonPlay::clear_chars() {
  chars_.Clear();
}
inline const ::MSG::CharData_& PlayDungeonNot_DungeonPlay::chars(int index) const {
  // @@protoc_insertion_point(field_get:MSG.PlayDungeonNot.DungeonPlay.chars)
  return chars_.Get(index);
}
inline ::MSG::CharData_* PlayDungeonNot_DungeonPlay::mutable_chars(int index) {
  // @@protoc_insertion_point(field_mutable:MSG.PlayDungeonNot.DungeonPlay.chars)
  return chars_.Mutable(index);
}
inline ::MSG::CharData_* PlayDungeonNot_DungeonPlay::add_chars() {
  // @@protoc_insertion_point(field_add:MSG.PlayDungeonNot.DungeonPlay.chars)
  return chars_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >*
PlayDungeonNot_DungeonPlay::mutable_chars() {
  // @@protoc_insertion_point(field_mutable_list:MSG.PlayDungeonNot.DungeonPlay.chars)
  return &chars_;
}
inline const ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >&
PlayDungeonNot_DungeonPlay::chars() const {
  // @@protoc_insertion_point(field_list:MSG.PlayDungeonNot.DungeonPlay.chars)
  return chars_;
}

// repeated .MSG.CharData_ mobs = 5;
inline int PlayDungeonNot_DungeonPlay::mobs_size() const {
  return mobs_.size();
}
inline void PlayDungeonNot_DungeonPlay::clear_mobs() {
  mobs_.Clear();
}
inline const ::MSG::CharData_& PlayDungeonNot_DungeonPlay::mobs(int index) const {
  // @@protoc_insertion_point(field_get:MSG.PlayDungeonNot.DungeonPlay.mobs)
  return mobs_.Get(index);
}
inline ::MSG::CharData_* PlayDungeonNot_DungeonPlay::mutable_mobs(int index) {
  // @@protoc_insertion_point(field_mutable:MSG.PlayDungeonNot.DungeonPlay.mobs)
  return mobs_.Mutable(index);
}
inline ::MSG::CharData_* PlayDungeonNot_DungeonPlay::add_mobs() {
  // @@protoc_insertion_point(field_add:MSG.PlayDungeonNot.DungeonPlay.mobs)
  return mobs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >*
PlayDungeonNot_DungeonPlay::mutable_mobs() {
  // @@protoc_insertion_point(field_mutable_list:MSG.PlayDungeonNot.DungeonPlay.mobs)
  return &mobs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >&
PlayDungeonNot_DungeonPlay::mobs() const {
  // @@protoc_insertion_point(field_list:MSG.PlayDungeonNot.DungeonPlay.mobs)
  return mobs_;
}

// -------------------------------------------------------------------

// PlayDungeonNot

// repeated .MSG.PlayDungeonNot.DungeonPlay plays = 1;
inline int PlayDungeonNot::plays_size() const {
  return plays_.size();
}
inline void PlayDungeonNot::clear_plays() {
  plays_.Clear();
}
inline const ::MSG::PlayDungeonNot_DungeonPlay& PlayDungeonNot::plays(int index) const {
  // @@protoc_insertion_point(field_get:MSG.PlayDungeonNot.plays)
  return plays_.Get(index);
}
inline ::MSG::PlayDungeonNot_DungeonPlay* PlayDungeonNot::mutable_plays(int index) {
  // @@protoc_insertion_point(field_mutable:MSG.PlayDungeonNot.plays)
  return plays_.Mutable(index);
}
inline ::MSG::PlayDungeonNot_DungeonPlay* PlayDungeonNot::add_plays() {
  // @@protoc_insertion_point(field_add:MSG.PlayDungeonNot.plays)
  return plays_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::MSG::PlayDungeonNot_DungeonPlay >*
PlayDungeonNot::mutable_plays() {
  // @@protoc_insertion_point(field_mutable_list:MSG.PlayDungeonNot.plays)
  return &plays_;
}
inline const ::google::protobuf::RepeatedPtrField< ::MSG::PlayDungeonNot_DungeonPlay >&
PlayDungeonNot::plays() const {
  // @@protoc_insertion_point(field_list:MSG.PlayDungeonNot.plays)
  return plays_;
}

// -------------------------------------------------------------------

// CreateCharReq

// optional uint32 charNo = 1;
inline void CreateCharReq::clear_charno() {
  charno_ = 0u;
}
inline ::google::protobuf::uint32 CreateCharReq::charno() const {
  // @@protoc_insertion_point(field_get:MSG.CreateCharReq.charNo)
  return charno_;
}
inline void CreateCharReq::set_charno(::google::protobuf::uint32 value) {
  
  charno_ = value;
  // @@protoc_insertion_point(field_set:MSG.CreateCharReq.charNo)
}

// -------------------------------------------------------------------

// CreateCharAns

// optional .MSG.ErrorCode err = 1;
inline void CreateCharAns::clear_err() {
  err_ = 0;
}
inline ::MSG::ErrorCode CreateCharAns::err() const {
  // @@protoc_insertion_point(field_get:MSG.CreateCharAns.err)
  return static_cast< ::MSG::ErrorCode >(err_);
}
inline void CreateCharAns::set_err(::MSG::ErrorCode value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:MSG.CreateCharAns.err)
}

// optional .MSG.CharData_ char_ = 2;
inline bool CreateCharAns::has_char_() const {
  return !_is_default_instance_ && char__ != NULL;
}
inline void CreateCharAns::clear_char_() {
  if (GetArenaNoVirtual() == NULL && char__ != NULL) delete char__;
  char__ = NULL;
}
inline const ::MSG::CharData_& CreateCharAns::char_() const {
  // @@protoc_insertion_point(field_get:MSG.CreateCharAns.char_)
  return char__ != NULL ? *char__ : *default_instance_->char__;
}
inline ::MSG::CharData_* CreateCharAns::mutable_char_() {
  
  if (char__ == NULL) {
    char__ = new ::MSG::CharData_;
  }
  // @@protoc_insertion_point(field_mutable:MSG.CreateCharAns.char_)
  return char__;
}
inline ::MSG::CharData_* CreateCharAns::release_char_() {
  // @@protoc_insertion_point(field_release:MSG.CreateCharAns.char_)
  
  ::MSG::CharData_* temp = char__;
  char__ = NULL;
  return temp;
}
inline void CreateCharAns::set_allocated_char_(::MSG::CharData_* char_) {
  delete char__;
  char__ = char_;
  if (char_) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MSG.CreateCharAns.char_)
}

// -------------------------------------------------------------------

// CurrencyNot

// optional uint32 vc1 = 1;
inline void CurrencyNot::clear_vc1() {
  vc1_ = 0u;
}
inline ::google::protobuf::uint32 CurrencyNot::vc1() const {
  // @@protoc_insertion_point(field_get:MSG.CurrencyNot.vc1)
  return vc1_;
}
inline void CurrencyNot::set_vc1(::google::protobuf::uint32 value) {
  
  vc1_ = value;
  // @@protoc_insertion_point(field_set:MSG.CurrencyNot.vc1)
}

// optional uint32 vc2 = 2;
inline void CurrencyNot::clear_vc2() {
  vc2_ = 0u;
}
inline ::google::protobuf::uint32 CurrencyNot::vc2() const {
  // @@protoc_insertion_point(field_get:MSG.CurrencyNot.vc2)
  return vc2_;
}
inline void CurrencyNot::set_vc2(::google::protobuf::uint32 value) {
  
  vc2_ = value;
  // @@protoc_insertion_point(field_set:MSG.CurrencyNot.vc2)
}

// optional uint32 vc3 = 3;
inline void CurrencyNot::clear_vc3() {
  vc3_ = 0u;
}
inline ::google::protobuf::uint32 CurrencyNot::vc3() const {
  // @@protoc_insertion_point(field_get:MSG.CurrencyNot.vc3)
  return vc3_;
}
inline void CurrencyNot::set_vc3(::google::protobuf::uint32 value) {
  
  vc3_ = value;
  // @@protoc_insertion_point(field_set:MSG.CurrencyNot.vc3)
}

// -------------------------------------------------------------------

// PlayDungeonReq

// optional uint32 dungeonNo = 1;
inline void PlayDungeonReq::clear_dungeonno() {
  dungeonno_ = 0u;
}
inline ::google::protobuf::uint32 PlayDungeonReq::dungeonno() const {
  // @@protoc_insertion_point(field_get:MSG.PlayDungeonReq.dungeonNo)
  return dungeonno_;
}
inline void PlayDungeonReq::set_dungeonno(::google::protobuf::uint32 value) {
  
  dungeonno_ = value;
  // @@protoc_insertion_point(field_set:MSG.PlayDungeonReq.dungeonNo)
}

// optional uint32 tier = 2;
inline void PlayDungeonReq::clear_tier() {
  tier_ = 0u;
}
inline ::google::protobuf::uint32 PlayDungeonReq::tier() const {
  // @@protoc_insertion_point(field_get:MSG.PlayDungeonReq.tier)
  return tier_;
}
inline void PlayDungeonReq::set_tier(::google::protobuf::uint32 value) {
  
  tier_ = value;
  // @@protoc_insertion_point(field_set:MSG.PlayDungeonReq.tier)
}

// -------------------------------------------------------------------

// PlayDungeonAns

// optional .MSG.ErrorCode err = 1;
inline void PlayDungeonAns::clear_err() {
  err_ = 0;
}
inline ::MSG::ErrorCode PlayDungeonAns::err() const {
  // @@protoc_insertion_point(field_get:MSG.PlayDungeonAns.err)
  return static_cast< ::MSG::ErrorCode >(err_);
}
inline void PlayDungeonAns::set_err(::MSG::ErrorCode value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:MSG.PlayDungeonAns.err)
}

// repeated .MSG.BattleData_ battles = 2;
inline int PlayDungeonAns::battles_size() const {
  return battles_.size();
}
inline void PlayDungeonAns::clear_battles() {
  battles_.Clear();
}
inline const ::MSG::BattleData_& PlayDungeonAns::battles(int index) const {
  // @@protoc_insertion_point(field_get:MSG.PlayDungeonAns.battles)
  return battles_.Get(index);
}
inline ::MSG::BattleData_* PlayDungeonAns::mutable_battles(int index) {
  // @@protoc_insertion_point(field_mutable:MSG.PlayDungeonAns.battles)
  return battles_.Mutable(index);
}
inline ::MSG::BattleData_* PlayDungeonAns::add_battles() {
  // @@protoc_insertion_point(field_add:MSG.PlayDungeonAns.battles)
  return battles_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::MSG::BattleData_ >*
PlayDungeonAns::mutable_battles() {
  // @@protoc_insertion_point(field_mutable_list:MSG.PlayDungeonAns.battles)
  return &battles_;
}
inline const ::google::protobuf::RepeatedPtrField< ::MSG::BattleData_ >&
PlayDungeonAns::battles() const {
  // @@protoc_insertion_point(field_list:MSG.PlayDungeonAns.battles)
  return battles_;
}

// repeated .MSG.CharData_ chars = 3;
inline int PlayDungeonAns::chars_size() const {
  return chars_.size();
}
inline void PlayDungeonAns::clear_chars() {
  chars_.Clear();
}
inline const ::MSG::CharData_& PlayDungeonAns::chars(int index) const {
  // @@protoc_insertion_point(field_get:MSG.PlayDungeonAns.chars)
  return chars_.Get(index);
}
inline ::MSG::CharData_* PlayDungeonAns::mutable_chars(int index) {
  // @@protoc_insertion_point(field_mutable:MSG.PlayDungeonAns.chars)
  return chars_.Mutable(index);
}
inline ::MSG::CharData_* PlayDungeonAns::add_chars() {
  // @@protoc_insertion_point(field_add:MSG.PlayDungeonAns.chars)
  return chars_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >*
PlayDungeonAns::mutable_chars() {
  // @@protoc_insertion_point(field_mutable_list:MSG.PlayDungeonAns.chars)
  return &chars_;
}
inline const ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >&
PlayDungeonAns::chars() const {
  // @@protoc_insertion_point(field_list:MSG.PlayDungeonAns.chars)
  return chars_;
}

// repeated .MSG.CharData_ mobs = 4;
inline int PlayDungeonAns::mobs_size() const {
  return mobs_.size();
}
inline void PlayDungeonAns::clear_mobs() {
  mobs_.Clear();
}
inline const ::MSG::CharData_& PlayDungeonAns::mobs(int index) const {
  // @@protoc_insertion_point(field_get:MSG.PlayDungeonAns.mobs)
  return mobs_.Get(index);
}
inline ::MSG::CharData_* PlayDungeonAns::mutable_mobs(int index) {
  // @@protoc_insertion_point(field_mutable:MSG.PlayDungeonAns.mobs)
  return mobs_.Mutable(index);
}
inline ::MSG::CharData_* PlayDungeonAns::add_mobs() {
  // @@protoc_insertion_point(field_add:MSG.PlayDungeonAns.mobs)
  return mobs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >*
PlayDungeonAns::mutable_mobs() {
  // @@protoc_insertion_point(field_mutable_list:MSG.PlayDungeonAns.mobs)
  return &mobs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::MSG::CharData_ >&
PlayDungeonAns::mobs() const {
  // @@protoc_insertion_point(field_list:MSG.PlayDungeonAns.mobs)
  return mobs_;
}

// optional .MSG.BattleData_ winner = 5;
inline bool PlayDungeonAns::has_winner() const {
  return !_is_default_instance_ && winner_ != NULL;
}
inline void PlayDungeonAns::clear_winner() {
  if (GetArenaNoVirtual() == NULL && winner_ != NULL) delete winner_;
  winner_ = NULL;
}
inline const ::MSG::BattleData_& PlayDungeonAns::winner() const {
  // @@protoc_insertion_point(field_get:MSG.PlayDungeonAns.winner)
  return winner_ != NULL ? *winner_ : *default_instance_->winner_;
}
inline ::MSG::BattleData_* PlayDungeonAns::mutable_winner() {
  
  if (winner_ == NULL) {
    winner_ = new ::MSG::BattleData_;
  }
  // @@protoc_insertion_point(field_mutable:MSG.PlayDungeonAns.winner)
  return winner_;
}
inline ::MSG::BattleData_* PlayDungeonAns::release_winner() {
  // @@protoc_insertion_point(field_release:MSG.PlayDungeonAns.winner)
  
  ::MSG::BattleData_* temp = winner_;
  winner_ = NULL;
  return temp;
}
inline void PlayDungeonAns::set_allocated_winner(::MSG::BattleData_* winner) {
  delete winner_;
  winner_ = winner;
  if (winner) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MSG.PlayDungeonAns.winner)
}

// -------------------------------------------------------------------

// LevelupCharReq

// optional uint32 slotNo = 1;
inline void LevelupCharReq::clear_slotno() {
  slotno_ = 0u;
}
inline ::google::protobuf::uint32 LevelupCharReq::slotno() const {
  // @@protoc_insertion_point(field_get:MSG.LevelupCharReq.slotNo)
  return slotno_;
}
inline void LevelupCharReq::set_slotno(::google::protobuf::uint32 value) {
  
  slotno_ = value;
  // @@protoc_insertion_point(field_set:MSG.LevelupCharReq.slotNo)
}

// -------------------------------------------------------------------

// LevelupCharAns

// optional .MSG.ErrorCode err = 1;
inline void LevelupCharAns::clear_err() {
  err_ = 0;
}
inline ::MSG::ErrorCode LevelupCharAns::err() const {
  // @@protoc_insertion_point(field_get:MSG.LevelupCharAns.err)
  return static_cast< ::MSG::ErrorCode >(err_);
}
inline void LevelupCharAns::set_err(::MSG::ErrorCode value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:MSG.LevelupCharAns.err)
}

// optional .MSG.CharData_ char_ = 2;
inline bool LevelupCharAns::has_char_() const {
  return !_is_default_instance_ && char__ != NULL;
}
inline void LevelupCharAns::clear_char_() {
  if (GetArenaNoVirtual() == NULL && char__ != NULL) delete char__;
  char__ = NULL;
}
inline const ::MSG::CharData_& LevelupCharAns::char_() const {
  // @@protoc_insertion_point(field_get:MSG.LevelupCharAns.char_)
  return char__ != NULL ? *char__ : *default_instance_->char__;
}
inline ::MSG::CharData_* LevelupCharAns::mutable_char_() {
  
  if (char__ == NULL) {
    char__ = new ::MSG::CharData_;
  }
  // @@protoc_insertion_point(field_mutable:MSG.LevelupCharAns.char_)
  return char__;
}
inline ::MSG::CharData_* LevelupCharAns::release_char_() {
  // @@protoc_insertion_point(field_release:MSG.LevelupCharAns.char_)
  
  ::MSG::CharData_* temp = char__;
  char__ = NULL;
  return temp;
}
inline void LevelupCharAns::set_allocated_char_(::MSG::CharData_* char_) {
  delete char__;
  char__ = char_;
  if (char_) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MSG.LevelupCharAns.char_)
}

// -------------------------------------------------------------------

// TierupCharReq

// optional uint32 slotNo = 1;
inline void TierupCharReq::clear_slotno() {
  slotno_ = 0u;
}
inline ::google::protobuf::uint32 TierupCharReq::slotno() const {
  // @@protoc_insertion_point(field_get:MSG.TierupCharReq.slotNo)
  return slotno_;
}
inline void TierupCharReq::set_slotno(::google::protobuf::uint32 value) {
  
  slotno_ = value;
  // @@protoc_insertion_point(field_set:MSG.TierupCharReq.slotNo)
}

// -------------------------------------------------------------------

// TierupCharAns

// optional .MSG.ErrorCode err = 1;
inline void TierupCharAns::clear_err() {
  err_ = 0;
}
inline ::MSG::ErrorCode TierupCharAns::err() const {
  // @@protoc_insertion_point(field_get:MSG.TierupCharAns.err)
  return static_cast< ::MSG::ErrorCode >(err_);
}
inline void TierupCharAns::set_err(::MSG::ErrorCode value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:MSG.TierupCharAns.err)
}

// optional .MSG.CharData_ char_ = 2;
inline bool TierupCharAns::has_char_() const {
  return !_is_default_instance_ && char__ != NULL;
}
inline void TierupCharAns::clear_char_() {
  if (GetArenaNoVirtual() == NULL && char__ != NULL) delete char__;
  char__ = NULL;
}
inline const ::MSG::CharData_& TierupCharAns::char_() const {
  // @@protoc_insertion_point(field_get:MSG.TierupCharAns.char_)
  return char__ != NULL ? *char__ : *default_instance_->char__;
}
inline ::MSG::CharData_* TierupCharAns::mutable_char_() {
  
  if (char__ == NULL) {
    char__ = new ::MSG::CharData_;
  }
  // @@protoc_insertion_point(field_mutable:MSG.TierupCharAns.char_)
  return char__;
}
inline ::MSG::CharData_* TierupCharAns::release_char_() {
  // @@protoc_insertion_point(field_release:MSG.TierupCharAns.char_)
  
  ::MSG::CharData_* temp = char__;
  char__ = NULL;
  return temp;
}
inline void TierupCharAns::set_allocated_char_(::MSG::CharData_* char_) {
  delete char__;
  char__ = char_;
  if (char_) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MSG.TierupCharAns.char_)
}

// -------------------------------------------------------------------

// BattleLogReq

// optional uint64 lid = 1;
inline void BattleLogReq::clear_lid() {
  lid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BattleLogReq::lid() const {
  // @@protoc_insertion_point(field_get:MSG.BattleLogReq.lid)
  return lid_;
}
inline void BattleLogReq::set_lid(::google::protobuf::uint64 value) {
  
  lid_ = value;
  // @@protoc_insertion_point(field_set:MSG.BattleLogReq.lid)
}

// -------------------------------------------------------------------

// BattleLogAns

// optional .MSG.ErrorCode err = 1;
inline void BattleLogAns::clear_err() {
  err_ = 0;
}
inline ::MSG::ErrorCode BattleLogAns::err() const {
  // @@protoc_insertion_point(field_get:MSG.BattleLogAns.err)
  return static_cast< ::MSG::ErrorCode >(err_);
}
inline void BattleLogAns::set_err(::MSG::ErrorCode value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:MSG.BattleLogAns.err)
}

// repeated .MSG.DungeonPlayData_ data = 2;
inline int BattleLogAns::data_size() const {
  return data_.size();
}
inline void BattleLogAns::clear_data() {
  data_.Clear();
}
inline const ::MSG::DungeonPlayData_& BattleLogAns::data(int index) const {
  // @@protoc_insertion_point(field_get:MSG.BattleLogAns.data)
  return data_.Get(index);
}
inline ::MSG::DungeonPlayData_* BattleLogAns::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:MSG.BattleLogAns.data)
  return data_.Mutable(index);
}
inline ::MSG::DungeonPlayData_* BattleLogAns::add_data() {
  // @@protoc_insertion_point(field_add:MSG.BattleLogAns.data)
  return data_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::MSG::DungeonPlayData_ >*
BattleLogAns::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:MSG.BattleLogAns.data)
  return &data_;
}
inline const ::google::protobuf::RepeatedPtrField< ::MSG::DungeonPlayData_ >&
BattleLogAns::data() const {
  // @@protoc_insertion_point(field_list:MSG.BattleLogAns.data)
  return data_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace MSG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_game_2eproto__INCLUDED
