// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "login.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MSG {

namespace {

const ::google::protobuf::Descriptor* PingReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PingReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* PongAns_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PongAns_reflection_ = NULL;
const ::google::protobuf::Descriptor* LoginReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LoginReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* LoginAns_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LoginAns_reflection_ = NULL;
const ::google::protobuf::Descriptor* RegistReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RegistReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* RegistAns_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RegistAns_reflection_ = NULL;
const ::google::protobuf::Descriptor* VersionReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  VersionReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* VersionAns_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  VersionAns_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_login_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_login_2eproto() {
  protobuf_AddDesc_login_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "login.proto");
  GOOGLE_CHECK(file != NULL);
  PingReq_descriptor_ = file->message_type(0);
  static const int PingReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PingReq, sessionkey_),
  };
  PingReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PingReq_descriptor_,
      PingReq::default_instance_,
      PingReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(PingReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PingReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PingReq, _is_default_instance_));
  PongAns_descriptor_ = file->message_type(1);
  static const int PongAns_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PongAns, err_),
  };
  PongAns_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PongAns_descriptor_,
      PongAns::default_instance_,
      PongAns_offsets_,
      -1,
      -1,
      -1,
      sizeof(PongAns),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PongAns, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PongAns, _is_default_instance_));
  LoginReq_descriptor_ = file->message_type(2);
  static const int LoginReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginReq, name_),
  };
  LoginReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      LoginReq_descriptor_,
      LoginReq::default_instance_,
      LoginReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(LoginReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginReq, _is_default_instance_));
  LoginAns_descriptor_ = file->message_type(3);
  static const int LoginAns_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginAns, err_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginAns, sessionkey_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginAns, data_),
  };
  LoginAns_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      LoginAns_descriptor_,
      LoginAns::default_instance_,
      LoginAns_offsets_,
      -1,
      -1,
      -1,
      sizeof(LoginAns),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginAns, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginAns, _is_default_instance_));
  RegistReq_descriptor_ = file->message_type(4);
  static const int RegistReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegistReq, data_),
  };
  RegistReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      RegistReq_descriptor_,
      RegistReq::default_instance_,
      RegistReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(RegistReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegistReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegistReq, _is_default_instance_));
  RegistAns_descriptor_ = file->message_type(5);
  static const int RegistAns_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegistAns, err_),
  };
  RegistAns_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      RegistAns_descriptor_,
      RegistAns::default_instance_,
      RegistAns_offsets_,
      -1,
      -1,
      -1,
      sizeof(RegistAns),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegistAns, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegistAns, _is_default_instance_));
  VersionReq_descriptor_ = file->message_type(6);
  static const int VersionReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VersionReq, version_),
  };
  VersionReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      VersionReq_descriptor_,
      VersionReq::default_instance_,
      VersionReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(VersionReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VersionReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VersionReq, _is_default_instance_));
  VersionAns_descriptor_ = file->message_type(7);
  static const int VersionAns_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VersionAns, err_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VersionAns, contents_),
  };
  VersionAns_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      VersionAns_descriptor_,
      VersionAns::default_instance_,
      VersionAns_offsets_,
      -1,
      -1,
      -1,
      sizeof(VersionAns),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VersionAns, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VersionAns, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_login_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PingReq_descriptor_, &PingReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PongAns_descriptor_, &PongAns::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      LoginReq_descriptor_, &LoginReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      LoginAns_descriptor_, &LoginAns::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      RegistReq_descriptor_, &RegistReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      RegistAns_descriptor_, &RegistAns::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      VersionReq_descriptor_, &VersionReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      VersionAns_descriptor_, &VersionAns::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_login_2eproto() {
  delete PingReq::default_instance_;
  delete PingReq_reflection_;
  delete PongAns::default_instance_;
  delete PongAns_reflection_;
  delete LoginReq::default_instance_;
  delete LoginReq_reflection_;
  delete LoginAns::default_instance_;
  delete LoginAns_reflection_;
  delete RegistReq::default_instance_;
  delete RegistReq_reflection_;
  delete RegistAns::default_instance_;
  delete RegistAns_reflection_;
  delete VersionReq::default_instance_;
  delete VersionReq_reflection_;
  delete VersionAns::default_instance_;
  delete VersionAns_reflection_;
}

void protobuf_AddDesc_login_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_login_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::MSG::protobuf_AddDesc_common_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013login.proto\022\003MSG\032\014common.proto\"\035\n\007Ping"
    "Req\022\022\n\nsessionKey\030\001 \001(\t\"&\n\007PongAns\022\033\n\003er"
    "r\030\001 \001(\0162\016.MSG.ErrorCode\"\030\n\010LoginReq\022\014\n\004n"
    "ame\030\001 \001(\t\"Y\n\010LoginAns\022\033\n\003err\030\001 \001(\0162\016.MSG"
    ".ErrorCode\022\022\n\nsessionKey\030\002 \001(\t\022\034\n\004data\030\003"
    " \001(\0132\016.MSG.UserData_\")\n\tRegistReq\022\034\n\004dat"
    "a\030\001 \001(\0132\016.MSG.UserData_\"(\n\tRegistAns\022\033\n\003"
    "err\030\001 \001(\0162\016.MSG.ErrorCode\"\035\n\nVersionReq\022"
    "\017\n\007version\030\001 \001(\t\"K\n\nVersionAns\022\033\n\003err\030\001 "
    "\001(\0162\016.MSG.ErrorCode\022 \n\010contents\030\002 \003(\0132\016."
    "MSG.Contents_b\006proto3", 421);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "login.proto", &protobuf_RegisterTypes);
  PingReq::default_instance_ = new PingReq();
  PongAns::default_instance_ = new PongAns();
  LoginReq::default_instance_ = new LoginReq();
  LoginAns::default_instance_ = new LoginAns();
  RegistReq::default_instance_ = new RegistReq();
  RegistAns::default_instance_ = new RegistAns();
  VersionReq::default_instance_ = new VersionReq();
  VersionAns::default_instance_ = new VersionAns();
  PingReq::default_instance_->InitAsDefaultInstance();
  PongAns::default_instance_->InitAsDefaultInstance();
  LoginReq::default_instance_->InitAsDefaultInstance();
  LoginAns::default_instance_->InitAsDefaultInstance();
  RegistReq::default_instance_->InitAsDefaultInstance();
  RegistAns::default_instance_->InitAsDefaultInstance();
  VersionReq::default_instance_->InitAsDefaultInstance();
  VersionAns::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_login_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_login_2eproto {
  StaticDescriptorInitializer_login_2eproto() {
    protobuf_AddDesc_login_2eproto();
  }
} static_descriptor_initializer_login_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PingReq::kSessionKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PingReq::PingReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MSG.PingReq)
}

void PingReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PingReq::PingReq(const PingReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MSG.PingReq)
}

void PingReq::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  sessionkey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

PingReq::~PingReq() {
  // @@protoc_insertion_point(destructor:MSG.PingReq)
  SharedDtor();
}

void PingReq::SharedDtor() {
  sessionkey_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void PingReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PingReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PingReq_descriptor_;
}

const PingReq& PingReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_login_2eproto();
  return *default_instance_;
}

PingReq* PingReq::default_instance_ = NULL;

PingReq* PingReq::New(::google::protobuf::Arena* arena) const {
  PingReq* n = new PingReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PingReq::Clear() {
// @@protoc_insertion_point(message_clear_start:MSG.PingReq)
  sessionkey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool PingReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MSG.PingReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string sessionKey = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sessionkey()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->sessionkey().data(), this->sessionkey().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MSG.PingReq.sessionKey"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MSG.PingReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MSG.PingReq)
  return false;
#undef DO_
}

void PingReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MSG.PingReq)
  // optional string sessionKey = 1;
  if (this->sessionkey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sessionkey().data(), this->sessionkey().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MSG.PingReq.sessionKey");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->sessionkey(), output);
  }

  // @@protoc_insertion_point(serialize_end:MSG.PingReq)
}

::google::protobuf::uint8* PingReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MSG.PingReq)
  // optional string sessionKey = 1;
  if (this->sessionkey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sessionkey().data(), this->sessionkey().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MSG.PingReq.sessionKey");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->sessionkey(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:MSG.PingReq)
  return target;
}

int PingReq::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MSG.PingReq)
  int total_size = 0;

  // optional string sessionKey = 1;
  if (this->sessionkey().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->sessionkey());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PingReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MSG.PingReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PingReq* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PingReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MSG.PingReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MSG.PingReq)
    MergeFrom(*source);
  }
}

void PingReq::MergeFrom(const PingReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MSG.PingReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.sessionkey().size() > 0) {

    sessionkey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sessionkey_);
  }
}

void PingReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MSG.PingReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PingReq::CopyFrom(const PingReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MSG.PingReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PingReq::IsInitialized() const {

  return true;
}

void PingReq::Swap(PingReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PingReq::InternalSwap(PingReq* other) {
  sessionkey_.Swap(&other->sessionkey_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PingReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PingReq_descriptor_;
  metadata.reflection = PingReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PingReq

// optional string sessionKey = 1;
void PingReq::clear_sessionkey() {
  sessionkey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& PingReq::sessionkey() const {
  // @@protoc_insertion_point(field_get:MSG.PingReq.sessionKey)
  return sessionkey_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PingReq::set_sessionkey(const ::std::string& value) {
  
  sessionkey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MSG.PingReq.sessionKey)
}
 void PingReq::set_sessionkey(const char* value) {
  
  sessionkey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MSG.PingReq.sessionKey)
}
 void PingReq::set_sessionkey(const char* value, size_t size) {
  
  sessionkey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MSG.PingReq.sessionKey)
}
 ::std::string* PingReq::mutable_sessionkey() {
  
  // @@protoc_insertion_point(field_mutable:MSG.PingReq.sessionKey)
  return sessionkey_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PingReq::release_sessionkey() {
  // @@protoc_insertion_point(field_release:MSG.PingReq.sessionKey)
  
  return sessionkey_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PingReq::set_allocated_sessionkey(::std::string* sessionkey) {
  if (sessionkey != NULL) {
    
  } else {
    
  }
  sessionkey_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sessionkey);
  // @@protoc_insertion_point(field_set_allocated:MSG.PingReq.sessionKey)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PongAns::kErrFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PongAns::PongAns()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MSG.PongAns)
}

void PongAns::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PongAns::PongAns(const PongAns& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MSG.PongAns)
}

void PongAns::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  err_ = 0;
}

PongAns::~PongAns() {
  // @@protoc_insertion_point(destructor:MSG.PongAns)
  SharedDtor();
}

void PongAns::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PongAns::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PongAns::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PongAns_descriptor_;
}

const PongAns& PongAns::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_login_2eproto();
  return *default_instance_;
}

PongAns* PongAns::default_instance_ = NULL;

PongAns* PongAns::New(::google::protobuf::Arena* arena) const {
  PongAns* n = new PongAns;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PongAns::Clear() {
// @@protoc_insertion_point(message_clear_start:MSG.PongAns)
  err_ = 0;
}

bool PongAns::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MSG.PongAns)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .MSG.ErrorCode err = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_err(static_cast< ::MSG::ErrorCode >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MSG.PongAns)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MSG.PongAns)
  return false;
#undef DO_
}

void PongAns::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MSG.PongAns)
  // optional .MSG.ErrorCode err = 1;
  if (this->err() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->err(), output);
  }

  // @@protoc_insertion_point(serialize_end:MSG.PongAns)
}

::google::protobuf::uint8* PongAns::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MSG.PongAns)
  // optional .MSG.ErrorCode err = 1;
  if (this->err() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->err(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:MSG.PongAns)
  return target;
}

int PongAns::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MSG.PongAns)
  int total_size = 0;

  // optional .MSG.ErrorCode err = 1;
  if (this->err() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->err());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PongAns::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MSG.PongAns)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PongAns* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PongAns>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MSG.PongAns)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MSG.PongAns)
    MergeFrom(*source);
  }
}

void PongAns::MergeFrom(const PongAns& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MSG.PongAns)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.err() != 0) {
    set_err(from.err());
  }
}

void PongAns::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MSG.PongAns)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PongAns::CopyFrom(const PongAns& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MSG.PongAns)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PongAns::IsInitialized() const {

  return true;
}

void PongAns::Swap(PongAns* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PongAns::InternalSwap(PongAns* other) {
  std::swap(err_, other->err_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PongAns::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PongAns_descriptor_;
  metadata.reflection = PongAns_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PongAns

// optional .MSG.ErrorCode err = 1;
void PongAns::clear_err() {
  err_ = 0;
}
 ::MSG::ErrorCode PongAns::err() const {
  // @@protoc_insertion_point(field_get:MSG.PongAns.err)
  return static_cast< ::MSG::ErrorCode >(err_);
}
 void PongAns::set_err(::MSG::ErrorCode value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:MSG.PongAns.err)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LoginReq::kNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LoginReq::LoginReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MSG.LoginReq)
}

void LoginReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

LoginReq::LoginReq(const LoginReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MSG.LoginReq)
}

void LoginReq::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

LoginReq::~LoginReq() {
  // @@protoc_insertion_point(destructor:MSG.LoginReq)
  SharedDtor();
}

void LoginReq::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void LoginReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoginReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LoginReq_descriptor_;
}

const LoginReq& LoginReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_login_2eproto();
  return *default_instance_;
}

LoginReq* LoginReq::default_instance_ = NULL;

LoginReq* LoginReq::New(::google::protobuf::Arena* arena) const {
  LoginReq* n = new LoginReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LoginReq::Clear() {
// @@protoc_insertion_point(message_clear_start:MSG.LoginReq)
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool LoginReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MSG.LoginReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MSG.LoginReq.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MSG.LoginReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MSG.LoginReq)
  return false;
#undef DO_
}

void LoginReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MSG.LoginReq)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MSG.LoginReq.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // @@protoc_insertion_point(serialize_end:MSG.LoginReq)
}

::google::protobuf::uint8* LoginReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MSG.LoginReq)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MSG.LoginReq.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:MSG.LoginReq)
  return target;
}

int LoginReq::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MSG.LoginReq)
  int total_size = 0;

  // optional string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LoginReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MSG.LoginReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const LoginReq* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const LoginReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MSG.LoginReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MSG.LoginReq)
    MergeFrom(*source);
  }
}

void LoginReq::MergeFrom(const LoginReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MSG.LoginReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
}

void LoginReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MSG.LoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LoginReq::CopyFrom(const LoginReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MSG.LoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginReq::IsInitialized() const {

  return true;
}

void LoginReq::Swap(LoginReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LoginReq::InternalSwap(LoginReq* other) {
  name_.Swap(&other->name_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LoginReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LoginReq_descriptor_;
  metadata.reflection = LoginReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LoginReq

// optional string name = 1;
void LoginReq::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& LoginReq::name() const {
  // @@protoc_insertion_point(field_get:MSG.LoginReq.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LoginReq::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MSG.LoginReq.name)
}
 void LoginReq::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MSG.LoginReq.name)
}
 void LoginReq::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MSG.LoginReq.name)
}
 ::std::string* LoginReq::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:MSG.LoginReq.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* LoginReq::release_name() {
  // @@protoc_insertion_point(field_release:MSG.LoginReq.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LoginReq::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:MSG.LoginReq.name)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LoginAns::kErrFieldNumber;
const int LoginAns::kSessionKeyFieldNumber;
const int LoginAns::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LoginAns::LoginAns()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MSG.LoginAns)
}

void LoginAns::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  data_ = const_cast< ::MSG::UserData_*>(&::MSG::UserData_::default_instance());
}

LoginAns::LoginAns(const LoginAns& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MSG.LoginAns)
}

void LoginAns::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  err_ = 0;
  sessionkey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  data_ = NULL;
}

LoginAns::~LoginAns() {
  // @@protoc_insertion_point(destructor:MSG.LoginAns)
  SharedDtor();
}

void LoginAns::SharedDtor() {
  sessionkey_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete data_;
  }
}

void LoginAns::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoginAns::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LoginAns_descriptor_;
}

const LoginAns& LoginAns::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_login_2eproto();
  return *default_instance_;
}

LoginAns* LoginAns::default_instance_ = NULL;

LoginAns* LoginAns::New(::google::protobuf::Arena* arena) const {
  LoginAns* n = new LoginAns;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LoginAns::Clear() {
// @@protoc_insertion_point(message_clear_start:MSG.LoginAns)
  err_ = 0;
  sessionkey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && data_ != NULL) delete data_;
  data_ = NULL;
}

bool LoginAns::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MSG.LoginAns)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .MSG.ErrorCode err = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_err(static_cast< ::MSG::ErrorCode >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_sessionKey;
        break;
      }

      // optional string sessionKey = 2;
      case 2: {
        if (tag == 18) {
         parse_sessionKey:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sessionkey()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->sessionkey().data(), this->sessionkey().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MSG.LoginAns.sessionKey"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_data;
        break;
      }

      // optional .MSG.UserData_ data = 3;
      case 3: {
        if (tag == 26) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MSG.LoginAns)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MSG.LoginAns)
  return false;
#undef DO_
}

void LoginAns::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MSG.LoginAns)
  // optional .MSG.ErrorCode err = 1;
  if (this->err() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->err(), output);
  }

  // optional string sessionKey = 2;
  if (this->sessionkey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sessionkey().data(), this->sessionkey().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MSG.LoginAns.sessionKey");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->sessionkey(), output);
  }

  // optional .MSG.UserData_ data = 3;
  if (this->has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->data_, output);
  }

  // @@protoc_insertion_point(serialize_end:MSG.LoginAns)
}

::google::protobuf::uint8* LoginAns::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MSG.LoginAns)
  // optional .MSG.ErrorCode err = 1;
  if (this->err() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->err(), target);
  }

  // optional string sessionKey = 2;
  if (this->sessionkey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sessionkey().data(), this->sessionkey().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MSG.LoginAns.sessionKey");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->sessionkey(), target);
  }

  // optional .MSG.UserData_ data = 3;
  if (this->has_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->data_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:MSG.LoginAns)
  return target;
}

int LoginAns::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MSG.LoginAns)
  int total_size = 0;

  // optional .MSG.ErrorCode err = 1;
  if (this->err() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->err());
  }

  // optional string sessionKey = 2;
  if (this->sessionkey().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->sessionkey());
  }

  // optional .MSG.UserData_ data = 3;
  if (this->has_data()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->data_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LoginAns::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MSG.LoginAns)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const LoginAns* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const LoginAns>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MSG.LoginAns)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MSG.LoginAns)
    MergeFrom(*source);
  }
}

void LoginAns::MergeFrom(const LoginAns& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MSG.LoginAns)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.err() != 0) {
    set_err(from.err());
  }
  if (from.sessionkey().size() > 0) {

    sessionkey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sessionkey_);
  }
  if (from.has_data()) {
    mutable_data()->::MSG::UserData_::MergeFrom(from.data());
  }
}

void LoginAns::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MSG.LoginAns)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LoginAns::CopyFrom(const LoginAns& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MSG.LoginAns)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginAns::IsInitialized() const {

  return true;
}

void LoginAns::Swap(LoginAns* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LoginAns::InternalSwap(LoginAns* other) {
  std::swap(err_, other->err_);
  sessionkey_.Swap(&other->sessionkey_);
  std::swap(data_, other->data_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LoginAns::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LoginAns_descriptor_;
  metadata.reflection = LoginAns_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LoginAns

// optional .MSG.ErrorCode err = 1;
void LoginAns::clear_err() {
  err_ = 0;
}
 ::MSG::ErrorCode LoginAns::err() const {
  // @@protoc_insertion_point(field_get:MSG.LoginAns.err)
  return static_cast< ::MSG::ErrorCode >(err_);
}
 void LoginAns::set_err(::MSG::ErrorCode value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:MSG.LoginAns.err)
}

// optional string sessionKey = 2;
void LoginAns::clear_sessionkey() {
  sessionkey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& LoginAns::sessionkey() const {
  // @@protoc_insertion_point(field_get:MSG.LoginAns.sessionKey)
  return sessionkey_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LoginAns::set_sessionkey(const ::std::string& value) {
  
  sessionkey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MSG.LoginAns.sessionKey)
}
 void LoginAns::set_sessionkey(const char* value) {
  
  sessionkey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MSG.LoginAns.sessionKey)
}
 void LoginAns::set_sessionkey(const char* value, size_t size) {
  
  sessionkey_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MSG.LoginAns.sessionKey)
}
 ::std::string* LoginAns::mutable_sessionkey() {
  
  // @@protoc_insertion_point(field_mutable:MSG.LoginAns.sessionKey)
  return sessionkey_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* LoginAns::release_sessionkey() {
  // @@protoc_insertion_point(field_release:MSG.LoginAns.sessionKey)
  
  return sessionkey_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LoginAns::set_allocated_sessionkey(::std::string* sessionkey) {
  if (sessionkey != NULL) {
    
  } else {
    
  }
  sessionkey_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sessionkey);
  // @@protoc_insertion_point(field_set_allocated:MSG.LoginAns.sessionKey)
}

// optional .MSG.UserData_ data = 3;
bool LoginAns::has_data() const {
  return !_is_default_instance_ && data_ != NULL;
}
void LoginAns::clear_data() {
  if (GetArenaNoVirtual() == NULL && data_ != NULL) delete data_;
  data_ = NULL;
}
const ::MSG::UserData_& LoginAns::data() const {
  // @@protoc_insertion_point(field_get:MSG.LoginAns.data)
  return data_ != NULL ? *data_ : *default_instance_->data_;
}
::MSG::UserData_* LoginAns::mutable_data() {
  
  if (data_ == NULL) {
    data_ = new ::MSG::UserData_;
  }
  // @@protoc_insertion_point(field_mutable:MSG.LoginAns.data)
  return data_;
}
::MSG::UserData_* LoginAns::release_data() {
  // @@protoc_insertion_point(field_release:MSG.LoginAns.data)
  
  ::MSG::UserData_* temp = data_;
  data_ = NULL;
  return temp;
}
void LoginAns::set_allocated_data(::MSG::UserData_* data) {
  delete data_;
  data_ = data;
  if (data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MSG.LoginAns.data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RegistReq::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RegistReq::RegistReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MSG.RegistReq)
}

void RegistReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  data_ = const_cast< ::MSG::UserData_*>(&::MSG::UserData_::default_instance());
}

RegistReq::RegistReq(const RegistReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MSG.RegistReq)
}

void RegistReq::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  data_ = NULL;
}

RegistReq::~RegistReq() {
  // @@protoc_insertion_point(destructor:MSG.RegistReq)
  SharedDtor();
}

void RegistReq::SharedDtor() {
  if (this != default_instance_) {
    delete data_;
  }
}

void RegistReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RegistReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RegistReq_descriptor_;
}

const RegistReq& RegistReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_login_2eproto();
  return *default_instance_;
}

RegistReq* RegistReq::default_instance_ = NULL;

RegistReq* RegistReq::New(::google::protobuf::Arena* arena) const {
  RegistReq* n = new RegistReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RegistReq::Clear() {
// @@protoc_insertion_point(message_clear_start:MSG.RegistReq)
  if (GetArenaNoVirtual() == NULL && data_ != NULL) delete data_;
  data_ = NULL;
}

bool RegistReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MSG.RegistReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .MSG.UserData_ data = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MSG.RegistReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MSG.RegistReq)
  return false;
#undef DO_
}

void RegistReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MSG.RegistReq)
  // optional .MSG.UserData_ data = 1;
  if (this->has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->data_, output);
  }

  // @@protoc_insertion_point(serialize_end:MSG.RegistReq)
}

::google::protobuf::uint8* RegistReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MSG.RegistReq)
  // optional .MSG.UserData_ data = 1;
  if (this->has_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->data_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:MSG.RegistReq)
  return target;
}

int RegistReq::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MSG.RegistReq)
  int total_size = 0;

  // optional .MSG.UserData_ data = 1;
  if (this->has_data()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->data_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RegistReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MSG.RegistReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const RegistReq* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const RegistReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MSG.RegistReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MSG.RegistReq)
    MergeFrom(*source);
  }
}

void RegistReq::MergeFrom(const RegistReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MSG.RegistReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.has_data()) {
    mutable_data()->::MSG::UserData_::MergeFrom(from.data());
  }
}

void RegistReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MSG.RegistReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RegistReq::CopyFrom(const RegistReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MSG.RegistReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RegistReq::IsInitialized() const {

  return true;
}

void RegistReq::Swap(RegistReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RegistReq::InternalSwap(RegistReq* other) {
  std::swap(data_, other->data_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RegistReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RegistReq_descriptor_;
  metadata.reflection = RegistReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RegistReq

// optional .MSG.UserData_ data = 1;
bool RegistReq::has_data() const {
  return !_is_default_instance_ && data_ != NULL;
}
void RegistReq::clear_data() {
  if (GetArenaNoVirtual() == NULL && data_ != NULL) delete data_;
  data_ = NULL;
}
const ::MSG::UserData_& RegistReq::data() const {
  // @@protoc_insertion_point(field_get:MSG.RegistReq.data)
  return data_ != NULL ? *data_ : *default_instance_->data_;
}
::MSG::UserData_* RegistReq::mutable_data() {
  
  if (data_ == NULL) {
    data_ = new ::MSG::UserData_;
  }
  // @@protoc_insertion_point(field_mutable:MSG.RegistReq.data)
  return data_;
}
::MSG::UserData_* RegistReq::release_data() {
  // @@protoc_insertion_point(field_release:MSG.RegistReq.data)
  
  ::MSG::UserData_* temp = data_;
  data_ = NULL;
  return temp;
}
void RegistReq::set_allocated_data(::MSG::UserData_* data) {
  delete data_;
  data_ = data;
  if (data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MSG.RegistReq.data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RegistAns::kErrFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RegistAns::RegistAns()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MSG.RegistAns)
}

void RegistAns::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

RegistAns::RegistAns(const RegistAns& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MSG.RegistAns)
}

void RegistAns::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  err_ = 0;
}

RegistAns::~RegistAns() {
  // @@protoc_insertion_point(destructor:MSG.RegistAns)
  SharedDtor();
}

void RegistAns::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RegistAns::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RegistAns::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RegistAns_descriptor_;
}

const RegistAns& RegistAns::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_login_2eproto();
  return *default_instance_;
}

RegistAns* RegistAns::default_instance_ = NULL;

RegistAns* RegistAns::New(::google::protobuf::Arena* arena) const {
  RegistAns* n = new RegistAns;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RegistAns::Clear() {
// @@protoc_insertion_point(message_clear_start:MSG.RegistAns)
  err_ = 0;
}

bool RegistAns::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MSG.RegistAns)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .MSG.ErrorCode err = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_err(static_cast< ::MSG::ErrorCode >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MSG.RegistAns)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MSG.RegistAns)
  return false;
#undef DO_
}

void RegistAns::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MSG.RegistAns)
  // optional .MSG.ErrorCode err = 1;
  if (this->err() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->err(), output);
  }

  // @@protoc_insertion_point(serialize_end:MSG.RegistAns)
}

::google::protobuf::uint8* RegistAns::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MSG.RegistAns)
  // optional .MSG.ErrorCode err = 1;
  if (this->err() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->err(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:MSG.RegistAns)
  return target;
}

int RegistAns::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MSG.RegistAns)
  int total_size = 0;

  // optional .MSG.ErrorCode err = 1;
  if (this->err() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->err());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RegistAns::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MSG.RegistAns)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const RegistAns* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const RegistAns>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MSG.RegistAns)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MSG.RegistAns)
    MergeFrom(*source);
  }
}

void RegistAns::MergeFrom(const RegistAns& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MSG.RegistAns)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.err() != 0) {
    set_err(from.err());
  }
}

void RegistAns::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MSG.RegistAns)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RegistAns::CopyFrom(const RegistAns& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MSG.RegistAns)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RegistAns::IsInitialized() const {

  return true;
}

void RegistAns::Swap(RegistAns* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RegistAns::InternalSwap(RegistAns* other) {
  std::swap(err_, other->err_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RegistAns::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RegistAns_descriptor_;
  metadata.reflection = RegistAns_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RegistAns

// optional .MSG.ErrorCode err = 1;
void RegistAns::clear_err() {
  err_ = 0;
}
 ::MSG::ErrorCode RegistAns::err() const {
  // @@protoc_insertion_point(field_get:MSG.RegistAns.err)
  return static_cast< ::MSG::ErrorCode >(err_);
}
 void RegistAns::set_err(::MSG::ErrorCode value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:MSG.RegistAns.err)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int VersionReq::kVersionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VersionReq::VersionReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MSG.VersionReq)
}

void VersionReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

VersionReq::VersionReq(const VersionReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MSG.VersionReq)
}

void VersionReq::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

VersionReq::~VersionReq() {
  // @@protoc_insertion_point(destructor:MSG.VersionReq)
  SharedDtor();
}

void VersionReq::SharedDtor() {
  version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void VersionReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* VersionReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return VersionReq_descriptor_;
}

const VersionReq& VersionReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_login_2eproto();
  return *default_instance_;
}

VersionReq* VersionReq::default_instance_ = NULL;

VersionReq* VersionReq::New(::google::protobuf::Arena* arena) const {
  VersionReq* n = new VersionReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void VersionReq::Clear() {
// @@protoc_insertion_point(message_clear_start:MSG.VersionReq)
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool VersionReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MSG.VersionReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string version = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_version()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->version().data(), this->version().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MSG.VersionReq.version"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MSG.VersionReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MSG.VersionReq)
  return false;
#undef DO_
}

void VersionReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MSG.VersionReq)
  // optional string version = 1;
  if (this->version().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->version().data(), this->version().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MSG.VersionReq.version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->version(), output);
  }

  // @@protoc_insertion_point(serialize_end:MSG.VersionReq)
}

::google::protobuf::uint8* VersionReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MSG.VersionReq)
  // optional string version = 1;
  if (this->version().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->version().data(), this->version().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MSG.VersionReq.version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->version(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:MSG.VersionReq)
  return target;
}

int VersionReq::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MSG.VersionReq)
  int total_size = 0;

  // optional string version = 1;
  if (this->version().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->version());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void VersionReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MSG.VersionReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const VersionReq* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const VersionReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MSG.VersionReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MSG.VersionReq)
    MergeFrom(*source);
  }
}

void VersionReq::MergeFrom(const VersionReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MSG.VersionReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.version().size() > 0) {

    version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
}

void VersionReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MSG.VersionReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VersionReq::CopyFrom(const VersionReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MSG.VersionReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VersionReq::IsInitialized() const {

  return true;
}

void VersionReq::Swap(VersionReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VersionReq::InternalSwap(VersionReq* other) {
  version_.Swap(&other->version_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata VersionReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = VersionReq_descriptor_;
  metadata.reflection = VersionReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// VersionReq

// optional string version = 1;
void VersionReq::clear_version() {
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& VersionReq::version() const {
  // @@protoc_insertion_point(field_get:MSG.VersionReq.version)
  return version_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void VersionReq::set_version(const ::std::string& value) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MSG.VersionReq.version)
}
 void VersionReq::set_version(const char* value) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MSG.VersionReq.version)
}
 void VersionReq::set_version(const char* value, size_t size) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MSG.VersionReq.version)
}
 ::std::string* VersionReq::mutable_version() {
  
  // @@protoc_insertion_point(field_mutable:MSG.VersionReq.version)
  return version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* VersionReq::release_version() {
  // @@protoc_insertion_point(field_release:MSG.VersionReq.version)
  
  return version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void VersionReq::set_allocated_version(::std::string* version) {
  if (version != NULL) {
    
  } else {
    
  }
  version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:MSG.VersionReq.version)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int VersionAns::kErrFieldNumber;
const int VersionAns::kContentsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VersionAns::VersionAns()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MSG.VersionAns)
}

void VersionAns::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

VersionAns::VersionAns(const VersionAns& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MSG.VersionAns)
}

void VersionAns::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  err_ = 0;
}

VersionAns::~VersionAns() {
  // @@protoc_insertion_point(destructor:MSG.VersionAns)
  SharedDtor();
}

void VersionAns::SharedDtor() {
  if (this != default_instance_) {
  }
}

void VersionAns::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* VersionAns::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return VersionAns_descriptor_;
}

const VersionAns& VersionAns::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_login_2eproto();
  return *default_instance_;
}

VersionAns* VersionAns::default_instance_ = NULL;

VersionAns* VersionAns::New(::google::protobuf::Arena* arena) const {
  VersionAns* n = new VersionAns;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void VersionAns::Clear() {
// @@protoc_insertion_point(message_clear_start:MSG.VersionAns)
  err_ = 0;
  contents_.Clear();
}

bool VersionAns::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MSG.VersionAns)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .MSG.ErrorCode err = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_err(static_cast< ::MSG::ErrorCode >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_contents;
        break;
      }

      // repeated .MSG.Contents_ contents = 2;
      case 2: {
        if (tag == 18) {
         parse_contents:
          DO_(input->IncrementRecursionDepth());
         parse_loop_contents:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_contents()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_contents;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MSG.VersionAns)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MSG.VersionAns)
  return false;
#undef DO_
}

void VersionAns::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MSG.VersionAns)
  // optional .MSG.ErrorCode err = 1;
  if (this->err() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->err(), output);
  }

  // repeated .MSG.Contents_ contents = 2;
  for (unsigned int i = 0, n = this->contents_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->contents(i), output);
  }

  // @@protoc_insertion_point(serialize_end:MSG.VersionAns)
}

::google::protobuf::uint8* VersionAns::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MSG.VersionAns)
  // optional .MSG.ErrorCode err = 1;
  if (this->err() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->err(), target);
  }

  // repeated .MSG.Contents_ contents = 2;
  for (unsigned int i = 0, n = this->contents_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->contents(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:MSG.VersionAns)
  return target;
}

int VersionAns::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MSG.VersionAns)
  int total_size = 0;

  // optional .MSG.ErrorCode err = 1;
  if (this->err() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->err());
  }

  // repeated .MSG.Contents_ contents = 2;
  total_size += 1 * this->contents_size();
  for (int i = 0; i < this->contents_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->contents(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void VersionAns::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MSG.VersionAns)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const VersionAns* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const VersionAns>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MSG.VersionAns)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MSG.VersionAns)
    MergeFrom(*source);
  }
}

void VersionAns::MergeFrom(const VersionAns& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MSG.VersionAns)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  contents_.MergeFrom(from.contents_);
  if (from.err() != 0) {
    set_err(from.err());
  }
}

void VersionAns::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MSG.VersionAns)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VersionAns::CopyFrom(const VersionAns& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MSG.VersionAns)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VersionAns::IsInitialized() const {

  return true;
}

void VersionAns::Swap(VersionAns* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VersionAns::InternalSwap(VersionAns* other) {
  std::swap(err_, other->err_);
  contents_.UnsafeArenaSwap(&other->contents_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata VersionAns::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = VersionAns_descriptor_;
  metadata.reflection = VersionAns_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// VersionAns

// optional .MSG.ErrorCode err = 1;
void VersionAns::clear_err() {
  err_ = 0;
}
 ::MSG::ErrorCode VersionAns::err() const {
  // @@protoc_insertion_point(field_get:MSG.VersionAns.err)
  return static_cast< ::MSG::ErrorCode >(err_);
}
 void VersionAns::set_err(::MSG::ErrorCode value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:MSG.VersionAns.err)
}

// repeated .MSG.Contents_ contents = 2;
int VersionAns::contents_size() const {
  return contents_.size();
}
void VersionAns::clear_contents() {
  contents_.Clear();
}
const ::MSG::Contents_& VersionAns::contents(int index) const {
  // @@protoc_insertion_point(field_get:MSG.VersionAns.contents)
  return contents_.Get(index);
}
::MSG::Contents_* VersionAns::mutable_contents(int index) {
  // @@protoc_insertion_point(field_mutable:MSG.VersionAns.contents)
  return contents_.Mutable(index);
}
::MSG::Contents_* VersionAns::add_contents() {
  // @@protoc_insertion_point(field_add:MSG.VersionAns.contents)
  return contents_.Add();
}
::google::protobuf::RepeatedPtrField< ::MSG::Contents_ >*
VersionAns::mutable_contents() {
  // @@protoc_insertion_point(field_mutable_list:MSG.VersionAns.contents)
  return &contents_;
}
const ::google::protobuf::RepeatedPtrField< ::MSG::Contents_ >&
VersionAns::contents() const {
  // @@protoc_insertion_point(field_list:MSG.VersionAns.contents)
  return contents_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace MSG

// @@protoc_insertion_point(global_scope)
